# Generated by Django 4.1.3 on 2023-01-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_accountmodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
