# Generated by Django 4.1.3 on 2022-12-31 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseapp.subcategory'),
        ),
    ]
