# Generated by Django 4.1.3 on 2023-01-28 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_product_alter_category_created_at_delete_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 23, 50, 46, 610134)),
        ),
    ]
