# Generated by Django 4.1.4 on 2023-01-31 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_alter_category_cat_image_alter_category_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 21, 58, 29, 463151)),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
